# -*- coding: utf-8 -*-
"""time_series_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Raxr5CKtwKxQSExQfhxP4FE0LWAtlahO

- Let's import important libraries
"""

import pandas as pd
import yfinance as yf
import datetime
from datetime import date, timedelta

"""- Here, we will use Yahoo Finance API to extract the latest stock price data."""

today = date.today()

d1 = today.strftime("%Y-%m-%d")
end_date = d1
d2 = date.today() - timedelta(days=720)
d2 = d2.strftime("%Y-%m-%d")
start_date = d2

data = yf.download('AAPL',
                      start=start_date,
                      end=end_date,
                      progress=False)
print(data.head())

"""- Let's visualize a line plot to see trends in stock prices of Apple:"""

import plotly.express as px

figure = px.line(data, x = data.index, y = 'Close', title = 'Time Series Analysis (line plot)')
figure.show()

"""- The above plot shows us detailed trends in the close prices of Apple from 2022-2024."""

import plotly.graph_objects as go

figure = go.Figure(data=[go.Candlestick(x = data.index,
                                        open = data["Open"],
                                        high = data["High"],
                                        low = data["Low"],
                                        close = data["Close"])])
figure.update_layout(title = "Time Series Analysis (candlestick chart)",
                     xaxis_rangeslider_visible = False)
figure.show()

"""- The above plot helps us to visualize a candlestick chart to see the trends in open, high, low and close prices of Apple.
- The red line indicate a fall in prices while the green line indicates rise in prices.
"""

figure = px.bar(data, x = data.index,
                y = "Close",
                title = "Time Series Analysis (bar plot)" )
figure.show()

"""- The above bar plot shows trends of close prices from July 2022 to Januray 2024.
- We observe that there is an increase in stock prices in the long-term scenario.

_____________________________________
_Note:_ A line-chart and candlestick both show us an increase/decrease in price, but if we need to see the price increase/decrease in long-term, we should prefer  a bar chart.
"""

figure = px.line(data, x = data.index,
                 y = 'Open',
                 range_x = ['2022-06-01','2022-12-31'],
                 title = "Time Series Analysis (custom date range)")
figure.show()

"""- The above plot analyzes opening stock prices between 2 specific dates."""

figure = go.Figure(data = [go.Candlestick(x = data.index,
                                        open = data["Open"],
                                        high = data["High"],
                                        low = data["Low"],
                                        close = data["Close"])])
figure.update_layout(title = "Time Series Analysis (Candlestick Chart with Buttons and Slider)")

figure.update_xaxes(
    rangeslider_visible = True,
    rangeselector = dict(
        buttons = list([
            dict(count = 1, label = "1m", step = "month", stepmode = "backward"),
            dict(count = 6, label = "6m", step = "month", stepmode = "backward"),
            dict(count = 1, label = "YTD", step = "year", stepmode = "todate"),
            dict(count = 1, label = "1y", step = "year", stepmode = "backward"),
            dict(step = "all")
        ])
    )
)
figure.show()

"""- In the above plot, we add a slider below our candlestick chart to make it interactive.
- We can control time intervals manually here by adjusting the slider.
"""